name: APK Derleyici
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: JDK 17 Kur
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gerekli Paketleri Kur
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo6 cmake libffi-dev libssl-dev \
          aidl python3-pip python3-setuptools
          pip3 install --user --upgrade Cython==0.29.33 buildozer

      - name: APK'yi Insa Et
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer -v android debug
          
      - name: APK'yi Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: Yazili-Cevaplari-Final-APK
          path: bin/*.apk
